org.gradle.jvmargs             = -Xmx4G
org.gradle.parallel            = true
org.gradle.configuration-cache = false

# Fabric
minecraft_version              = 26.3
loader_version                 = 0.19.5
loom_version                   = 1.17-SNAPSHOT
fabric_version                 = 0.161.0+26.3

# Mod
mod_id                         = siftec
mod_name                       = SIFTEC
mod_version                    = 0.1.0
maven_group                    = com.meakaandre
archives_base_name             = siftec
